//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_COMERCIAL_ANEXO
    {
        public int CRCA_CD_ID { get; set; }
        public int CRMC_CD_ID { get; set; }
        public System.DateTime CRCA_DT_ANEXO { get; set; }
        public string CRCA_NM_TITULO { get; set; }
        public int CRCA_IN_TIPO { get; set; }
        public string CRCA_AQ_ARQUIVO { get; set; }
        public int CRCA_IN_ATIVO { get; set; }
    
        public virtual CRM_COMERCIAL CRM_COMERCIAL { get; set; }
    }
}
