//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_COMERCIAL_COMENTARIO_NOVA
    {
        public int CRCC_CD_ID { get; set; }
        public int CRMC_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime CRCC_DT_COMENTARIO { get; set; }
        public string CRCC_DS_COMENTARIO { get; set; }
        public int CRCC_IN_ATIVO { get; set; }
    
        public virtual CRM_COMERCIAL CRM_COMERCIAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
