//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PROPOSTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_PROPOSTA()
        {
            this.CRM_PROPOSTA_ACOMPANHAMENTO = new HashSet<CRM_PROPOSTA_ACOMPANHAMENTO>();
        }
    
        public int CRPR_CD_ID { get; set; }
        public int CRM1_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime CRPR_DT_PROPOSTA { get; set; }
        public System.DateTime CRPR_DT_VALIDADE { get; set; }
        public string CRPR_DS_INFORMACOES { get; set; }
        public int CRPR_IN_STATUS { get; set; }
        public string CRPR_TX_TEXTO { get; set; }
        public string CRPR_AQ_ARQUIVO { get; set; }
        public Nullable<int> TEPR_CD_ID { get; set; }
        public Nullable<System.DateTime> CRPR_DT_CANCELAMENTO { get; set; }
        public string CRPR_DS_CANCELAMENTO { get; set; }
        public Nullable<System.DateTime> CRPR_DT_REPROVACAO { get; set; }
        public string CRPR_DS_REPROVACAO { get; set; }
        public Nullable<System.DateTime> CRPR_DT_APROVACAO { get; set; }
        public string CRPR_DS_APROVACAO { get; set; }
        public int CRPR_IN_ATIVO { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<System.DateTime> CRPR_DT_ENVIO { get; set; }
    
        public virtual CRM CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_PROPOSTA_ACOMPANHAMENTO> CRM_PROPOSTA_ACOMPANHAMENTO { get; set; }
        public virtual TEMPLATE_PROPOSTA TEMPLATE_PROPOSTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
