//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PROPOSTA_ACOMPANHAMENTO
    {
        public int PRAC_CD_ID { get; set; }
        public int CRPR_CD_ID { get; set; }
        public System.DateTime PRAC_DT_ACOMPANHAMENTO { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PRAC_TX_ACOMPANHAMENTO { get; set; }
        public int PRAC_IN_ATIVO { get; set; }
    
        public virtual CRM_PROPOSTA CRM_PROPOSTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
