//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO_HISTORICO
    {
        public int DOHI_CD_ID { get; set; }
        public int DOCU_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime DOHI_DT_ACESSO { get; set; }
        public int ASSI_CD_ID { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
