//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO_RESPOSTA_ACAO
    {
        public int FRAC_CD_ID { get; set; }
        public int FORE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID2 { get; set; }
        public string FRAC_NM_TITULO { get; set; }
        public string FRAC_DS_DESCRICAO { get; set; }
        public System.DateTime FRAC_DT_CRIACAO { get; set; }
        public Nullable<System.DateTime> FRAC_DT_PREVISTA { get; set; }
        public int FRAC_IN_STATUS { get; set; }
        public int FRAC_IN_ATIVO { get; set; }
    
        public virtual FORMULARIO_RESPOSTA FORMULARIO_RESPOSTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
