//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO_RESPOSTA
    {
        public int FORE_CD_ID { get; set; }
        public Nullable<System.DateTime> FORE_DT_CADASTRO { get; set; }
        public string FORE_NM_NOME { get; set; }
        public string FORE_NM_EMAIL { get; set; }
        public string FORE_NR_CELULAR { get; set; }
        public Nullable<int> FORE_IN_MENSAGERIA { get; set; }
        public Nullable<int> FORE_IN_CRM { get; set; }
        public Nullable<int> FORE_IN_PATRIMONIO { get; set; }
        public Nullable<int> FORE_IN_ESTOQUE { get; set; }
        public Nullable<int> FORE_IN_COMPRA { get; set; }
        public Nullable<int> FORE_IN_VENDA { get; set; }
        public Nullable<int> FORE_IN_SERVICEDESK { get; set; }
        public Nullable<int> FORE_IN_FATURAMENTO { get; set; }
        public Nullable<int> FORE_IN_FINANCEIRO { get; set; }
        public Nullable<int> FORE_IN_EXPEDICAO { get; set; }
        public Nullable<int> FORE_IN_DOCUMENTO { get; set; }
        public string FORE_TX_MENSAGEM { get; set; }
        public Nullable<int> FORE_IN_ATIVO { get; set; }
        public Nullable<int> FORE_IN_STATUS { get; set; }
        public string FORE_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
    
        public virtual UF UF { get; set; }
    }
}
