//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO_RESPOSTA_COMENTARIO
    {
        public int FRCO_CD_ID { get; set; }
        public int FORE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime FRCO_DT_COMENTARIO { get; set; }
        public string FRCO_DS_COMENTARIO { get; set; }
        public int FRCO_IN_ATIVO { get; set; }
    
        public virtual FORMULARIO_RESPOSTA FORMULARIO_RESPOSTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
